### ISSUE TITLE
ekim21's to-do list

### ISSUE THREAD

**Issue by ekim21** [githubteacher/oct-04-dev#10]
- [x] Created an issue 
- make tiers
  - [x] Created a branch 
  - [x] Work locally
- [ ] work remotely
- [ ] mess with pull requests
- [ ] have a good time
