### ISSUE TITLE
adutta2 ToDo List

### ISSUE THREAD

**Issue by adutta2** [githubteacher/oct-04-dev#15]
- [x] Make ToDo List
- [ ] Understand Markdown better
  - [ ] How to Emoji
- [ ] Figure out merging branches
- [ ] Understand advantages of GitHub Desktop vs Git Bash vs PowerShell
- [ ] Figure out if Ford prefers SSH or HTTPS

**Comment by JasonMick** [comment]
[jmick] +1
