### ISSUE TITLE
udenjoe's todo list

### ISSUE THREAD

**Issue by udenjoe** [githubteacher/oct-04-dev#4]
- [x] Create an issue
- [x] Create a branch 
- [x] Work Locally
- [x] Work on the Remote
- [x] Mess with Pull Requests
- [x] Have a good time?

**Comment by udenjoe** [comment]
Updated check boxes after closing.
