### ISSUE TITLE
githubteacher's todo list

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/oct-04-dev#8]
- [x] Create an issue
- Working with Branches
  - [ ] Work Locally
  - [ ] Work on the Remote
- [ ] Mess with Pull Requests
- [ ] Have a good time?
