### ISSUE TITLE
nzxhvr's todo list

### ISSUE THREAD

**Issue by devops23345** [githubteacher/oct-04-dev#9]
- [x] Get more coffee
- [x] Create an issue
- [x] Work locally
- [x] Work remote
- [x] Mess with Pull Requests

**Comment by devops23345** [comment]
Completed all tasks
